"""add pending field

Revision ID: 18d71b841071
Revises: 
Create Date: 2025-05-04 13:39:40.476992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18d71b841071'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('battery_status', schema=None) as batch_op:
        batch_op.alter_column('voltage',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)

    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peding', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.drop_column('peding')

    with op.batch_alter_table('battery_status', schema=None) as batch_op:
        batch_op.alter_column('voltage',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
