"""remove field

Revision ID: a076f5127358
Revises: ab0c79b1a33f
Create Date: 2025-05-04 14:29:16.832817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a076f5127358'
down_revision = 'ab0c79b1a33f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
