"""add was_sent and last_sent_at

Revision ID: ab0c79b1a33f
Revises: bc9f4a24cb53
Create Date: 2025-05-04 14:26:58.658530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab0c79b1a33f'
down_revision = 'bc9f4a24cb53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('was_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.drop_column('last_sent_at')
        batch_op.drop_column('was_sent')

    # ### end Alembic commands ###
