"""typo

Revision ID: bc9f4a24cb53
Revises: fd2e133f5322
Create Date: 2025-05-04 14:13:28.018817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc9f4a24cb53'
down_revision = 'fd2e133f5322'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.drop_column('source')

    # ### end Alembic commands ###
