"""typo

Revision ID: fd2e133f5322
Revises: 18d71b841071
Create Date: 2025-05-04 13:40:34.837121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd2e133f5322'
down_revision = '18d71b841071'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pending', sa.Boolean(), nullable=True))
        batch_op.drop_column('peding')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('display_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peding', sa.BOOLEAN(), nullable=True))
        batch_op.drop_column('pending')

    # ### end Alembic commands ###
